config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  
  resources :books

  resources :authors
  
  namespace :admin do
   resources :users
  end

scope module: 'editores' do 
  resources :categories
end

resources :users do
  resources :books, :borrowings
end
  

resources :editorials do
  resources :books

end

resources :authors do 
  resources :books
end
  

  

 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categorias = Category.all
  end

  def show
    @categoria = Category.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/editores/categories_controller.rb
class Editores::CategoriesController < ApplicationController
  def index
    @categorias = Category.all
  end

  def show
    @categoria = Category.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/editores/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/editores/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/editores/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/editores/categories/index.html.erb
<table>
        <thead>
                <tr>
                    <th>Categoria</th>
                    <th>Descripcion</th>
                </tr>
        </thead>
        <tbody>
            <% @categorias.each do |categoria| %>
                <tr>
                    <td><%= categoria.id %></td>
                    <td><%= categoria.categoria %></td>
                    <td><%= categoria.descripcion %></td>
                    <td><%= link_to "Mostrar", action: 'show', id: categoria.id %></td>
                </tr>
            <%end%>
        </tbody>
           
</table>

app/views/editores/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/editores/categories/show.html.erb
<h1>Mostrar datos de la categoria</h1>
<hr>
<%= link_to 'volver', categories_path %>
<h3><strong>Categoria: </strong><%= @categoria.categoria %></h3>
<h3><strong>Descripcion: </strong><%= @categoria.descripcion %></h3>
<hr>