config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  
  resources :books

  resources :authors
  
  namespace :admin do
   resources :users
  end

scope module: 'editores' do 
  resources :categories
end

resources :users do
  resources :books, :borrowings
end
  

resources :editorials do
  resources :books

end

resources :authors do 
  resources :books
end
  

  

 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    #validar que cada autor tenga nombre,nacinalidad, e idioma
    validates :nombre,:nacionalidad,:idioma, presence: {message: "Dato necesario"}

    #valida que el nombre de cada autor sea minnimo 2, maximo 50 caracteres
    validates :nombre, length: {minimum: 2, maximum: 50, message: "minimo 2 y maximo 50 caracteres"}

    #Validar que la nacinaliadd de cada autor sea entre 2 y 24 caracteres
    validates :nacionalidad, length: {in: 2..25, message: "Minimo 2, maximo 25"}

    #validar el registro de ganancias anuales es de cada autor sea numerico
    validates :ganancias_anuales,numericality:{message: "El dato debe ser numerico"}

     has_many :books
    #valida que cuando se cree o actualice un libro por medio de la relacion entre autor, tambien se realicen las validaciones del modelo book
    validates_associated :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  layout "layout_author"
  
  def index
    @autores = Author.all 
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    #se reocoge el hash con los datos del autor
    datos_autor = params[:author]

    #se recoge cada uno de los datos del autor
    nombre_autor = datos_autor[:nombre]
    nac_autor = datos_autor[:nacionalidad]
    idioma_autor = datos_autor[:idioma]
    ganacias_autor = datos_autor[:ganacias_anuales]

    #en base a los datos llegados como parametro se crea un nuevo modelo autor
    @author = Author.new(nombre: nombre_autor,nacionalidad: nac_autor,idioma: idioma_autor,ganacias_anuales: ganacias_autor)

    #por ultimo el modelo recientemente creado se guarda en la base de datos
    @author.save
    redirect_to author_path(@author)

  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    datos_autor = params[:author]

    nombre_autor = datos_autor[:nombre]
    nac_autor = datos_autor[:nacionalidad]
    idioma_autor = datos_autor[:idioma]
    ganacias_autor = datos_autor[:ganacias_anuales]

    if @author.update(nombre: nombre_autor, nacionalidad: nac_autor,idioma: idioma_autor, ganacias_anuales: ganacias_autor)
        redirect_to author_path(@author)
    else  
       render :edit
    end
  end

  def destroy
    #modifique le metodo destroy
    @author = Author.find_by_id(params[:id])
    @author.delete
    redirect_to authors_path

  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_autor.html.erb
        <tr>
            <td><%= autor.id %></td>
            <td><%= autor.nombre %></td>
            <td><%= autor.nacionalidad %></td>
            <td><%= autor.idioma %></td>
            
            <td><%= link_to "Mostrar", author_path(autor)%></td>
            <td><%= link_to "Editar", edit_author_path(autor) %></td>
            <td><%= link_to "Borrar",autor, method: :delete, data: {confirm: '¿Quieres borrar este autor ?'} %></td>
        </tr>       
      

app/views/authors/_form.html.erb
<%= form_for @author, html: {class:" css_class"} do |f| %>
 <label><strong>Nombre: </strong></label>
 <%= f.text_field :nombre %>
 <br><br>
<label><strong>Nacionalidad: </strong></label>
 <%= f.text_field :nacionalidad %>
<br><br>
<label><strong>Idioma: </strong></label>
<%= f.text_field :idioma%>
<br><br>
<label><strong>Ganancias anuales </strong></label>
<%= f.text_field :ganacias_anuales %>
<br><br>

<%= f.submit @author.new_record?? "Crear" : "Actualizar" %>

<% end %>

app/views/authors/edit.html.erb
<%= link_to 'volver a la lista', authors_path %>
<h1>Editar autor</h1>
<br>
<%= render 'form' %>

app/views/authors/index.html.erb
<%= link_to "Crear autor", new_author_path %>
<br/>
<table>
    <thead>
          <tr>
                <th>ID autor</th>
                <th>Nombre</th>
                <th>Nacionalidad</th>
                <th>Idioma</th>
                <th>Acciones</th>
          </tr>
    </thead>
    <tbody>
      <!-- render partial es el formulario y @autores es la variable de instancia que viene desde controller authors index-->
       <%= render partial: "autor", collection: @autores %>
    </tbody>
</table>

app/views/authors/new.html.erb
<br>
<br>
<%= link_to 'Volver a la lista',authors_path %>
<h1>Crear nuevo autor</h1>
<br>
<%= render 'form' %>

app/views/authors/show.html.erb
<%= link_to 'Volver a la lista', authors_path %>

<%= link_to 'Editar', edit_author_path %>
<h1>Mostrar datos de autor</h1>
<h3><strong>Id:</strong><%= @author.id %></h3>
<h3><strong>Nombre:</strong> <%= @author.nombre %></h3>
<h3><strong>Nacionalidad:</strong> <%= @author.nacionalidad %></h3>
<h3><strong>Idioma:</strong> <%= @author.idioma %></h3>
<h3><strongs>Ganancia annual: <%= @author.ganacias_anuales %> $</strongs></h3>