config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  
  resources :books

  resources :authors
  
  namespace :admin do
   resources :users
  end

scope module: 'editores' do 
  resources :categories
end

resources :users do
  resources :books, :borrowings
end
  

resources :editorials do
  resources :books

end

resources :authors do 
  resources :books
end
  

  

 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :category
  belongs_to :author
  belongs_to :editorial

  has_many :borrowings
  has_many :users, through: :borrowings
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 layout "layout_book"
 
  def index
    if params[:editorial_id]
      @books =  Editorial.find(params[:editorial_id]).books
      elsif params[:author_id]
        
        @books = Author.find(params[:author_id]).books
        
         
      else
          @books = Book.all
      end

  
  end

  def show
   if params[:editorial_id]
        @book =  Editorial.find(params[:editorial_id]).books.find(params[:id])
      else
          @book = Book.find(params[:id])
      end
  end

  def new
      @book = Book.new
  end

  def create
    datos_libro =  params[:book]

    titulo_lib = datos_libro[:titulo]
    idioma_lib = datos_libro[:idioma]
    paginas_lib = datos_libro[:paginas]
    descripcion_lib = datos_libro[:descripcion]
    autor_lib = datos_libro[:author_id]
    categoria_lib = datos_libro[:category_id]
    editorial_lib = datos_libro[:editorial_id]

   @book = Book.new(titulo: titulo_lib, idioma: idioma_lib, paginas: paginas_lib, descripcion: descripcion_lib, author_id: autor_lib, category_id: categoria_lib, editorial_id: editorial_lib)
    if @book.valid?
        @book.save
        redirect_to books_path
    else
       render :edit
       
    end
    
         
    
    end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    #Busca primero el dato
    @book = Book.find(params[:id])

    #Recoge los datos recibidos mediante un hash
    datos_libro = params[:book]


    titulo_lib = datos_libro[:titulo]
    idioma_lib = datos_libro[:idioma]
    paginas_lib = datos_libro[:paginas]
    descripcion_lib = datos_libro[:descripcion]
    autor_lib = datos_libro[:author_id]
    categoria_lib = datos_libro[:category_id]
    editorial_lib = datos_libro[:editorial_id]

    if @book.update(titulo: titulo_lib, idioma: idioma_lib, paginas: paginas_lib, descripcion: descripcion_lib, author_id: autor_lib, category_id: categoria_lib, editorial_id: editorial_lib)
      redirect_to book_path(@book)
    else
      render :edit
    end


  end

  def destroy
    

   @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: {class:" css_class"} do |f| %>
 <label><strong>Titulo: </strong></label>
 <%= f.text_field :titulo %>
 <br><br>
<label><strong>Idioma: </strong></label>
<%= f.text_field :idioma %>

<br><br>
<label><strong>Paginas: </strong></label>
<%= f.text_field :paginas %>
<br><br>
<label><strong>Descricpcion: </strong></label>
<%= f.text_field :descripcion %>
<br><br>
<label><strong>Autor: </strong></label>
<%= f.text_field :author_id %>
<br><br>
<label><strong>Categoria:  </strong></label>
<%= f.text_field :category_id %>
<br><br>
<label><strong>Editorial: </strong></label>
<%= f.text_field :editorial_id %>
<br><br>

<%= f.submit @book.new_record?? "Ingresar" : "Actualizar" %>



<% end %>

app/views/books/_libro.html.erb
      
     <tr> 
                <td><%= libro.id %></td>
                <td><%= libro.titulo %></td>
                <td><%= libro.idioma %></td>
                <td><%= libro.paginas %></td>
                <td><%= libro.descripcion %></td>

                 <%unless libro.author.nil?  %>
                <td> <%=libro.author.nombre %> </td> 
                <%end%>  
                 <%unless libro.category.nil?  %>
                <td> <%=libro.category.categoria %> </td> 
                <%end%> 
                  <%unless libro.editorial.nil?  %>
                <td> <%=libro.editorial.nombre %> </td> 
                <%end%> 
                <td><%= link_to "Mostrar", action: 'show', id: libro.id %></td>
                <td><%= link_to "Editar",edit_book_path(libro) %></td>
                <td><%= link_to "Eliminar",libro, method: :delete, data: {confirm: 'Quieres eliminar este libro ?'} %></td>
    </tr>   

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/delete.html.erb
<h1>Books#delete</h1>
<p>Find me in app/views/books/delete.html.erb</p>

app/views/books/edit.html.erb
<%= link_to 'Volver a la lista',books_path %>
<h1>Editar Libro</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<%= link_to 'Ingresar libro', new_book_path%>

<table>
    <thead>
          <tr>
              <th>Id</th>
              <th>Titulo</th>
              <th>Idioma</th>
              <th>Paginas</th>
              <th>Descripcion</th>
              <th>Autor</th>
              <th>Categoria</th>
              <th>Editorial</th>

          </tr>
    </thead>
    <tbody>
    <!--render partial: libro es el formulario _form de books y @books es la variable de instancia que viene del controlador books del metodof index -->
    <%= render partial: "libro", collection: @books %>
    </tbody>
</table>

app/views/books/new.html.erb
<%= link_to 'Volver a la lista',books_path %>
<h1>Ingresar Nuevo Libro</h1>
<hr>
<%= render 'form' %>

app/views/books/show.html.erb
<%= link_to 'Volver',books_path%>
<hr>
    <h3><strong>Titulo: </strong><%= @book.titulo %></h3>
    <h3><strong>Idioma: </strong><%= @book.idioma %></h3>
    <h3><strong>Paginas: </strong><%= @book.paginas %></h3>
    <h3><strong>Autor: </strong><%unless @book.author.nil? %><%= @book.author.nombre %> <%end%></h3>
    <h3><strong>Categoria: </strong><%unless @book.category.nil? %><%= @book.category.categoria %> <%end%></h3>
    <h3><strong>Editorial: </strong><%unless @book.editorial.nil? %><%= @book.editorial.nombre %> <%end%></h3>
     <h3><strong>Descripcion: </strong><%= @book.descripcion %></h3>
<hr>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>