config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  
  resources :books

  resources :authors
  
  namespace :admin do
   resources :users
  end

scope module: 'editores' do 
  resources :categories
end

resources :users do
  resources :books, :borrowings
end
  

resources :editorials do
  resources :books

end

resources :authors do 
  resources :books
end
  

  

 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/editorial.rb
class Editorial < ApplicationRecord
    has_many :books, dependent: :destroy

   # before_destroy :verificar_lib

    def self.verificar_fk

        join  = Book.joins(:editorial).where('editorials.id' => :id)

        if join.exists?
            return true
        else
            return false
        end
        
        #join.each do |dato|
         #   puts "#{dato.titulo} Autor: #{dato.nombre} "
        #end


     #  existe = Book.where(editorial_id: Editorial.where("id="+id.to_s)).count
     

       
    end
   

end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  def index
    @editoriales = Editorial.all
  end

  def show
    @editorial = Editorial.find(params[:id])
  end

  def new
    @editorial = Editorial.new
  end

  def create
    datos_editorial = params[:editorial]

    nom_editorial = datos_editorial[:nombre]
    pais_editorial = datos_editorial[:pais]
    tel_editorial = datos_editorial[:telefono]

    @editorial = Editorial.new(nombre: nom_editorial, pais: pais_editorial, telefono: tel_editorial)

    @editorial.save
    redirect_to editorial_path(@editorial)

  end

  def edit
      @editorial = Editorial.find(params[:id])
  end

  def update
    @editorial = Editorial.find(params[:id])

    datos_editorial = params[:editorial]

    nom_editorial = datos_editorial[:nombre]
    pais_editorial = datos_editorial[:pais]
    tel_editorial = datos_editorial[:telefono]

    if @editorial.update(nombre: nom_editorial, pais: pais_editorial, telefono: tel_editorial)
        redirect_to editorial_path(@editorial)
    else
      render :edit
    end


  end
#NO se que vergas hice con esto pero ya funciona me daba un error al momento de elimanar el dato ya que la tabla books contenia
#el id de editorial pero acomode en el modelo editorial esto :dependent => :destroy y le puse destroy en @editorial.destroy :v
  def destroy
  @editorial_id = Editorial.find(params[:id])
  
  books = Editorial.verificar_fk

    if books == true
       @editorial_id.destroy
       redirect_to editorials_path, notice: "Se elimino correctamente"
    else
        redirect_to editorials_path , notice: "No se pudo eliminar de la base de datos ya que se encuentra asociada con otro libro"
    end
       
 
  # if @editorial.destroy
  #   redirect_to editorials_path, notice: "Usuario elimnado"
 # else
  #  render :edit, notice: "Error"
  #end


  end


end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/views/editorials/_editorial.html.erb
 

 <tr>
    <td><%= editorial.id %></td>
    <td><%= editorial.nombre %></td>
    <td><%= editorial.pais %></td>
    <td><%= editorial.telefono %></td>
    <!--Voy a remplazar editorial_books_path(editorial) por editorial_path(editorial)-->
    <td><%= link_to 'Mostrar', editorial_path(editorial) %></td>
    <td> <%= link_to 'Mostrar libro', editorial_books_path(editorial) %></td>
    <td><%= link_to 'Editar', edit_editorial_path(editorial) %></td>
    <td><%= link_to 'Eliminar',editorial, method: :delete, data: {confirm: 'Quieres Borrar ? '}%></td>
    

</tr>

app/views/editorials/_form.html.erb
<%= form_for @editorial, html: {class:" css_class"} do |f| %>
<label><strong>Nombre: </strong></label>
<%= f.text_field :nombre %>
<br><br>
<label><strong>Pais: </strong></label>
<%= f.text_field :pais %>
<br><br>
<label><strong>Telefono: </strong></label>
<%= f.text_field :telefono %>
<br><br>

<%= f.submit @editorial.new_record?? "Ingresar" : "Actualizar" %>



    

<% end %>

app/views/editorials/create.html.erb
<h1>Editorials#create</h1>
<p>Find me in app/views/editorials/create.html.erb</p>

app/views/editorials/delete.html.erb
<h1>Editorials#delete</h1>
<p>Find me in app/views/editorials/delete.html.erb</p>

app/views/editorials/edit.html.erb
<h1>Editar editorial</h1>
<hr>
<br>
<%= link_to 'Volver al menu', editorials_path %>
<br><br>
<%= render 'form' %>

app/views/editorials/index.html.erb
<br>
<br>
<%= flash[:notice] %>
<%= link_to 'Ingresar Nuevo', new_editorial_path %>
 
<table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Pais</th>
                <th>Telefono</th>
            </tr>
        
        </thead>
        
        <tbody>
        
         <%= render partial: "editorial" , collection: @editoriales%>
        </tbody>


</table>

app/views/editorials/new.html.erb
<br><br>
<%= link_to 'Volver', editorials_path %>
<hr>
<h1>Registro de nueva editorial</h1>

<%= render 'form' %>

app/views/editorials/show.html.erb
<h1>Editorial Mostrada</h1>
<%= link_to "Volver", editorials_path %>
<hr> 
<h3><strong>Nombre: </strong><%= @editorial.nombre %></h3>
<h3><Strong>Pais: </Strong><%= @editorial.pais %></h3>
<h3><strong>Telefono: </strong><%= @editorial.telefono %></h3>
<hr>

app/views/editorials/update.html.erb
<h1>Editorials#update</h1>
<p>Find me in app/views/editorials/update.html.erb</p>